// Church slug helpers.
//
// URLs went from /admin/churches/<uuid>/team to /admin/churches/MJACENTRAL/team.
// The DB column is `churches.slug` — unique, NOT NULL, auto-generated by trigger.
//
// All client code that builds church URLs should use the SLUG, not the UUID.
// Old URLs with UUIDs still work — ChurchDetailsLayout detects a UUID param
// and redirects to the slug.

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export const isUuid = (s: string | null | undefined): boolean =>
  !!s && UUID_RE.test(s);

/**
 * Normalize whatever the user typed in an admin edit field to the
 * canonical slug shape: A-Z and 0-9 only, uppercase, max 20 chars.
 * Matches the DB trigger churches_ensure_slug exactly so client
 * preview and server-stored value agree.
 */
export const normalizeSlug = (raw: string): string => {
  if (!raw) return '';
  // Strip accents (NFD decompose + remove combining marks), uppercase,
  // strip everything that isn't A-Z / 0-9, truncate to 20.
  return raw
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toUpperCase()
    .replace(/[^A-Z0-9]/g, '')
    .slice(0, 20);
};

/**
 * Build a church-scoped URL: /admin/churches/<slug>/<path>.
 * Pass the slug (NOT the UUID). Helper exists so callers don't
 * accidentally hand off a UUID — there's a runtime check in dev.
 */
export const churchPath = (slugOrId: string, subpath: string): string => {
  if (import.meta.env.DEV && isUuid(slugOrId)) {
    // Surfaces during development if any call site still passes a UUID.
    // In prod we silently accept it (the page will redirect once loaded).
    console.warn('[churchPath] called with a UUID — please pass church.slug instead', { slugOrId, subpath });
  }
  const clean = subpath.startsWith('/') ? subpath.slice(1) : subpath;
  return `/admin/churches/${slugOrId}/${clean}`;
};

/**
 * Build the slug-canonical URL for a page the user landed on with a
 * UUID. Replaces the first UUID occurrence in the pathname and
 * preserves the query string + hash. Extracted from
 * useChurchBySlugOrId so the redirect math is testable without a
 * router / DOM.
 */
export const computeSlugRedirect = (
  pathname: string,
  search: string,
  hash: string,
  uuid: string,
  slug: string,
): string => pathname.replace(uuid, slug) + (search || '') + (hash || '');
